// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartDevice.Data;

namespace SmartDevice.Migrations.Rooms
{
    [DbContext(typeof(RoomsContext))]
    [Migration("20221114220257_RoomsMigretion")]
    partial class RoomsMigretion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartDevice.Models.RoomModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SmartDevice.Models.SmartDeviceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomModelId");

                    b.ToTable("SmartDeviceModel");
                });

            modelBuilder.Entity("SmartDevice.Models.SmartDeviceModel", b =>
                {
                    b.HasOne("SmartDevice.Models.RoomModel", null)
                        .WithMany("SmartDevices")
                        .HasForeignKey("RoomModelId");
                });

            modelBuilder.Entity("SmartDevice.Models.RoomModel", b =>
                {
                    b.Navigation("SmartDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
